services:
  - type: web
    name: attaendence-web
    env: python
    region: oregon
    branch: main
    buildCommand: python -m pip install --upgrade pip setuptools wheel cmake && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    pythonVersion: 3.11.18
